export abstract class Constants {
  public static token = 'token';
  public static refreshToken = 'refreshToken';
  public static userId = 'userId';
  public static creationDate = 'CreationDate';
  public static updationDate = 'UpdationDate';
  public static name = 'Name';
  public static isAdmin = 'IsAdmin';
  public static roleClaim = 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role';
  public static gameStash = 'GameStash';
  public static debtManager = 'DebtManager';
  public static admin = 'Admin';
  public static status = 'Status';
  public static kite = 'Kite';
  public static angelOne = 'AngelOne';
  public static angelOneAccessToken = 'angelOneAccessToken';
  public static angelOneRefreshToken = 'angelOneRefreshToken';
  public static angelOneFeedToken = 'angelOneFeedToken';
}
